// ERFAN-MD
import { fileURLToPath } from 'url';
import path from 'path';
import { cmd } from '../command.js';
import axios from 'axios';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// GPT-3.5 Turbo API Commands (20 variations)
cmd({ pattern: "gpt35", desc: "Ask GPT-3.5 Turbo AI.", category: "ai", react: "🤖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.gpt35 Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤖 *GPT-3.5 Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "gpt4", desc: "Ask GPT-4 AI model.", category: "ai", react: "🤖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.gpt4 Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤖 *GPT-4 Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "gpt4o", desc: "Ask GPT-4o AI model.", category: "ai", react: "🤖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.gpt4o Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤖 *GPT-4o Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "chatgpt", desc: "Ask ChatGPT AI.", category: "ai", react: "💬", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.chatgpt Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`💬 *ChatGPT Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "chatgptplus", desc: "Ask ChatGPT Plus AI.", category: "ai", react: "💬", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.chatgptplus Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`💬 *ChatGPT Plus Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "copilot", desc: "Ask GitHub Copilot AI.", category: "ai", react: "👨‍💻", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.copilot Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`👨‍💻 *Copilot Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "copilotpro", desc: "Ask GitHub Copilot Pro.", category: "ai", react: "👨‍💻", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.copilotpro Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`👨‍💻 *Copilot Pro Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "claude", desc: "Ask Claude AI assistant.", category: "ai", react: "🤖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.claude Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤖 *Claude Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "claudeopus", desc: "Ask Claude Opus AI.", category: "ai", react: "🤖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.claudeopus Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤖 *Claude Opus Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "gemini", desc: "Ask Google Gemini AI.", category: "ai", react: "♊", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.gemini Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`♊ *Gemini Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "geminipro", desc: "Ask Gemini Pro AI.", category: "ai", react: "♊", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.geminipro Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`♊ *Gemini Pro Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "grok", desc: "Ask Grok AI by xAI.", category: "ai", react: "🚀", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.grok Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🚀 *Grok Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "grokbeta", desc: "Ask Grok Beta AI.", category: "ai", react: "🚀", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.grokbeta Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🚀 *Grok Beta Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "deepseek", desc: "Ask DeepSeek AI.", category: "ai", react: "🔍", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.deepseek Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🔍 *DeepSeek Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "deepseekcoder", desc: "Ask DeepSeek Coder AI.", category: "ai", react: "💻", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.deepseekcoder Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`💻 *DeepSeek Coder Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "llama", desc: "Ask LLaMA AI model.", category: "ai", react: "🦙", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.llama Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🦙 *LLaMA Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "llama2", desc: "Ask LLaMA 2 AI.", category: "ai", react: "🦙", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.llama2 Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🦙 *LLaMA 2 Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "llama3", desc: "Ask LLaMA 3 AI.", category: "ai", react: "🦙", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.llama3 Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🦙 *LLaMA 3 Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "bard", desc: "Ask Google Bard AI.", category: "ai", react: "🎭", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.bard Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/gpt-3.5-turbo?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🎭 *Bard Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });

// Grammar Check API Commands (5 variations)
cmd({ pattern: "grammar", desc: "Check grammar and spelling.", category: "ai", react: "✍️", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.grammar Your text`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/grammarcheck?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); const r = data.result; reply(`✍️ *Grammar Check:*\n\n*Original:* ${r.original}\n*Corrected:* ${r.corrected}\n*Errors:* ${r.error_count}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "spellcheck", desc: "Check spelling errors.", category: "ai", react: "🔤", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.spellcheck Your text`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/grammarcheck?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); const r = data.result; reply(`🔤 *Spell Check:*\n\n*Original:* ${r.original}\n*Corrected:* ${r.corrected}\n*Errors:* ${r.error_count}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "correct", desc: "Correct text errors.", category: "ai", react: "✏️", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.correct Your text`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/grammarcheck?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); const r = data.result; reply(`✏️ *Text Correction:*\n\n*Original:* ${r.original}\n*Fixed:* ${r.corrected}\n*Errors:* ${r.error_count}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "grammarly", desc: "Advanced grammar check.", category: "ai", react: "📖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.grammarly Your text`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/grammarcheck?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); const r = data.result; reply(`📖 *Grammarly Check:*\n\n*Original:* ${r.original}\n*Improved:* ${r.corrected}\n*Issues:* ${r.error_count}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "proofread", desc: "Proofread your text.", category: "ai", react: "📝", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.proofread Your text`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/grammarcheck?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); const r = data.result; reply(`📝 *Proofreading:*\n\n*Original:* ${r.original}\n*Polished:* ${r.corrected}\n*Corrections:* ${r.error_count}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });

// Islamcity API Commands (5 variations)
cmd({ pattern: "islam", desc: "Get Islamic information.", category: "ai", react: "🕌", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.islam Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/islamcity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🕌 *Islamic Info:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "hadith", desc: "Search Hadith information.", category: "ai", react: "📿", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.hadith Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/islamcity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`📿 *Hadith Info:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "quran", desc: "Get Quran-related answers.", category: "ai", react: "📖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.quran Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/islamcity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`📖 *Quran Guidance:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "fiqh", desc: "Ask Fiqh questions.", category: "ai", react: "⚖️", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.fiqh Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/islamcity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`⚖️ *Fiqh Answer:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "sunnah", desc: "Learn about Sunnah.", category: "ai", react: "☪️", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.sunnah Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/islamcity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`☪️ *Sunnah Info:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });

// Kimi API Commands (5 variations)
cmd({ pattern: "kimi", desc: "Ask Kimi AI assistant.", category: "ai", react: "🤖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.kimi Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/kimi?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤖 *Kimi Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "kiamiga", desc: "Ask Kiamiga AI.", category: "ai", react: "🤖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.kiamiga Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/kimi?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤖 *Kiamiga Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "moonshot", desc: "Ask Moonshot AI.", category: "ai", react: "🌙", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.moonshot Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/kimi?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🌙 *Moonshot Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "kimihelp", desc: "Get Kimi AI help.", category: "ai", react: "🆘", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.kimihelp Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/kimi?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🆘 *Kimi Help:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "kimir", desc: "Ask Kimi R AI.", category: "ai", react: "🤖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.kimir Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/kimi?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤖 *Kimi R Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });

// Lumin API Commands (5 variations)
cmd({ pattern: "lumin", desc: "Ask Lumin AI assistant.", category: "ai", react: "💡", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.lumin Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/lumin?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`💡 *Lumin Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "lumina", desc: "Ask Lumina AI.", category: "ai", react: "✨", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.lumina Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/lumin?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`✨ *Lumina Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "lightai", desc: "Ask Light AI.", category: "ai", react: "🔦", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.lightai Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/lumin?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🔦 *Light AI Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "luminchat", desc: "Chat with Lumin AI.", category: "ai", react: "💬", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.luminchat Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/lumin?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`💬 *Lumin Chat:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "luminai", desc: "Ask Lumin AI.", category: "ai", react: "🤖", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.luminai Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/lumin?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤖 *Lumin AI Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });

// MathGPT API Commands (5 variations)
cmd({ pattern: "mathgpt", desc: "Get math assistance.", category: "ai", react: "🧮", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.mathgpt Your math problem`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/mathgpt?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🧮 *MathGPT:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "math", desc: "Solve math problems.", category: "ai", react: "➗", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.math Your math problem`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/mathgpt?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`➗ *Math Solver:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "calculator", desc: "AI calculator help.", category: "ai", react: "🧮", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.calculator Your calculation`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/mathgpt?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🧮 *AI Calculator:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "algebra", desc: "Get algebra help.", category: "ai", react: "📐", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.algebra Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/mathgpt?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`📐 *Algebra Help:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "geometry", desc: "Get geometry assistance.", category: "ai", react: "📏", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.geometry Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/mathgpt?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`📏 *Geometry Help:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });

// Perplexity API Commands (5 variations)
cmd({ pattern: "perplexity", desc: "Ask Perplexity AI.", category: "ai", react: "🤔", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.perplexity Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/perplexity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🤔 *Perplexity Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "perplex", desc: "Ask Perplex AI.", category: "ai", react: "❓", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.perplex Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/perplexity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`❓ *Perplex Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "askai", desc: "Ask AI anything.", category: "ai", react: "🎓", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.askai Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/perplexity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🎓 *AI Answer:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "brain", desc: "Ask Brain AI.", category: "ai", react: "🧠", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.brain Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/perplexity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`🧠 *Brain Says:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });
cmd({ pattern: "think", desc: "Ask Think AI.", category: "ai", react: "💭", filename: __filename }, async (conn, mek, m, { q, reply }) => { try { if (!q) return reply("💬 *Usage:* `.think Your question`"); const { data } = await axios.get(`https://api.nexray.eu.cc/ai/perplexity?text=${encodeURIComponent(q)}`); if (!data?.status) return reply("❌ API Error."); reply(`💭 *Think AI:*\n\n${data.result}\n\n~ DARKZONE-MD`); } catch (e) { console.error(e.message); reply("❌ Failed."); } });