// ERFAN-MD
import { fileURLToPath } from 'url';
import path from 'path';
import { cmd } from '../command.js';
import axios from 'axios';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

cmd({
    pattern: "iphonechat",
    alias: ["fakechat", "iphonefake", "fakess", "iphonescreenshot"],
    desc: "Generate fake iPhone chat screenshot",
    category: "maker",
    react: "📱",
    filename: __filename
}, async (conn, mek, m, { from, q, reply }) => {
    try {
        // Check if query is provided
        if (!q) return await reply("📱 *iPhone Fake Chat Generator*\n\nPlease provide text in format:\n.text|chatTime|statusBarTime\n\nExample:\n.iphonechat Hello World|22:11|22:20\n\nOr:\n.iphonechat ndul cantik|22:11|22:20");

        // Parse the query
        const parts = q.split('|');
        if (parts.length < 3) {
            return await reply("❌ *Invalid Format!*\n\nCorrect format:\n.text|chatTime|statusBarTime\n\nExample:\n.iphonechat How are you?|15:30|15:45");
        }

        const text = parts[0].trim();
        const chatTime = parts[1].trim();
        const statusBarTime = parts[2].trim();

        // Validate time format (basic check)
        const timeRegex = /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/;
        if (!timeRegex.test(chatTime) || !timeRegex.test(statusBarTime)) {
            return await reply("❌ *Invalid Time Format!*\n\nTime should be in HH:MM format (24-hour)\nExample: 14:30, 22:15, 09:45");
        }

        await conn.sendMessage(from, { react: { text: '⏳', key: m.key } });

        // Encode parameters
        const encodedText = encodeURIComponent(text);
        const encodedChatTime = encodeURIComponent(chatTime);
        const encodedStatusTime = encodeURIComponent(statusBarTime);

        // API URL
        const apiUrl = `https://api.deline.web.id/maker/iqc?text=${encodedText}&chatTime=${encodedChatTime}&statusBarTime=${encodedStatusTime}`;

        // Send processing message
        await reply(`📱 *Generating iPhone Screenshot...*\n\n• Text: ${text}\n• Chat Time: ${chatTime}\n• Status Time: ${statusBarTime}\n\nPlease wait...`);

        // Call API
        const response = await axios.get(apiUrl, {
            responseType: 'arraybuffer',
            timeout: 30000
        });

        if (!response.data || response.data.length === 0) {
            return await reply("❌ Failed to generate screenshot! API returned empty response.");
        }

        // Send the image
        await conn.sendMessage(from, {
            image: response.data,
            caption: `📱 *iPhone Fake Chat Screenshot*\n\n• Text: ${text}\n> Chat Time: ${chatTime}\n> Status Time: ${statusBarTime}\n\n> Generated by DARKZONE-MD`
        }, { quoted: mek });

        await conn.sendMessage(from, { react: { text: '✅', key: m.key } });

    } catch (error) {
        console.error("Error in iphonechat command:", error);
        
        if (error.code === 'ECONNABORTED') {
            await reply("❌ Request timeout! Please try again with shorter text.");
        } else if (error.response?.status === 404) {
            await reply("❌ API endpoint not found! Please check the API URL.");
        } else if (error.response?.status === 400) {
            await reply("❌ Bad request! Please check your input format.");
        } else {
            await reply("❌ Error occurred while generating screenshot! Please try again.");
        }
        
        await conn.sendMessage(from, { react: { text: '❌', key: m.key } });
    }
});
